import { TipoItem, EstadoItem } from "@/types/database";

export const TIPO_ITEM_LABELS: Record<TipoItem, string> = {
  analisis_contexto: "Análisis de Contexto",
  partes_interesadas: "Partes Interesadas",
  alcance_sgc: "Alcance del SGC",
  mapa_procesos: "Mapa de Procesos",
  politica: "Política de Calidad",
  roles_responsabilidades: "Roles y Responsabilidades",
  riesgos_oportunidades: "Riesgos y Oportunidades",
  objetivo: "Objetivo de Calidad",
  indicador: "Indicador (KPI)",
  infraestructura: "Infraestructura",
  instrumento: "Instrumento de Medición",
  competencia: "Competencia",
  capacitacion: "Capacitación",
  procedimiento: "Procedimiento",
  instructivo: "Instructivo",
  formulario: "Formulario",
  registro: "Registro",
  manual: "Manual",
  diseno_desarrollo: "Diseño y Desarrollo",
  evaluacion_proveedor: "Evaluación de Proveedor",
  producto_no_conforme: "Producto No Conforme",
  satisfaccion_cliente: "Satisfacción del Cliente",
  auditoria_interna: "Auditoría Interna",
  revision_direccion: "Revisión por Dirección",
  no_conformidad: "No Conformidad",
  accion_correctiva: "Acción Correctiva",
  mejora: "Mejora",
};

export const TIPO_ITEM_PREFIJOS: Record<TipoItem, string> = {
  analisis_contexto: "CTX",
  partes_interesadas: "PAR",
  alcance_sgc: "ALC",
  mapa_procesos: "MAP",
  politica: "POL",
  roles_responsabilidades: "ROL",
  riesgos_oportunidades: "RYO",
  objetivo: "OBJ",
  indicador: "IND",
  infraestructura: "INF",
  instrumento: "INS",
  competencia: "CMP",
  capacitacion: "CAP",
  procedimiento: "PRO",
  instructivo: "INS",
  formulario: "FOR",
  registro: "REG",
  manual: "MAN",
  diseno_desarrollo: "DSR",
  evaluacion_proveedor: "EPR",
  producto_no_conforme: "PNC",
  satisfaccion_cliente: "SAT",
  auditoria_interna: "AUD",
  revision_direccion: "RDI",
  no_conformidad: "NCR",
  accion_correctiva: "ACC",
  mejora: "MEJ",
};

export const TIPO_ITEM_CLAUSULA_PRINCIPAL: Record<TipoItem, string> = {
  analisis_contexto: "4.1",
  partes_interesadas: "4.2",
  alcance_sgc: "4.3",
  mapa_procesos: "4.4",
  politica: "5.2",
  roles_responsabilidades: "5.3",
  riesgos_oportunidades: "6.1",
  objetivo: "6.2",
  indicador: "9.1.3",
  infraestructura: "7.1.3",
  instrumento: "7.1.5",
  competencia: "7.2",
  capacitacion: "7.2",
  procedimiento: "7.5",
  instructivo: "7.5",
  formulario: "7.5",
  registro: "7.5",
  manual: "7.5",
  diseno_desarrollo: "8.3",
  evaluacion_proveedor: "8.4",
  producto_no_conforme: "8.7",
  satisfaccion_cliente: "9.1.2",
  auditoria_interna: "9.2",
  revision_direccion: "9.3",
  no_conformidad: "10.2",
  accion_correctiva: "10.2",
  mejora: "10.3",
};

export const TIPOS_REQUIEREN_APROBACION: TipoItem[] = [
  "politica",
  "manual",
  "procedimiento",
  "instructivo",
  "diseno_desarrollo",
];

export const ESTADO_LABELS: Record<EstadoItem, string> = {
  vigente: "Vigente",
  por_vencer: "Por vencer",
  vencido: "Vencido",
  obsoleto: "Obsoleto",
  pendiente_aprobacion: "Vigente",
  borrador: "Vigente",
};

export const ESTADO_COLORS: Record<EstadoItem, string> = {
  vigente: "success",
  por_vencer: "warning",
  vencido: "danger",
  obsoleto: "muted",
  pendiente_aprobacion: "success",
  borrador: "success",
};

export const FRECUENCIAS_COMUNES = [
  { label: "Mensual", dias: 30 },
  { label: "Trimestral", dias: 90 },
  { label: "Semestral", dias: 180 },
  { label: "Anual", dias: 365 },
  { label: "Bianual", dias: 730 },
];
